apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-computing-assignment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cloud-computing-assignment
        version: "v1"
    spec:
      containers:
        - name: cloud-computing-assignment
          image: 'gcr.io/fleet-resolver-237016/$APP_NAME:v1'
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /lazy
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
